Update to roman_numerals.c Fixed memory leaks
exercism/c pull request #750
Opened 2022-01-31 12:11 UTC by bobahop

In current configuration `make memcheck` reported direct memory leak for failed `TEST_ASSERT_EQUAL_STRING` on my local machine (Ubuntu WSL.) With the current configuration there are no memory leaks. Specifying `if (result) free result;` generated an error for attempted double free of `result`, so it must be getting successfully freed somewhere as long as the ASSERT passes.

2022-01-31 12:18 UTC, bobahop commented
This isn't ready yet. When testing with more than one test it leaks again. So looking into it...

2022-01-31 12:45 UTC, bobahop commented
Is working now for multiple tests.

2022-01-31 22:51 UTC, wolf99 approved these changes

2022-01-31 22:54 UTC, wolf99 commented
I'm not clear why this would be a memory leak.
As `result` is a local variable which is created and freed each time the function is called, where is it leaked?

2022-01-31 22:55 UTC, wolf99 requested changes
Sorry, I was too hasty with approval. I would like to confirm my understanding with you first per the previous comment on the PR

2022-02-01 01:11 UTC, ryanplusplus commented
> I'm not clear why this would be a memory leak. As `result` is a local variable which is created and freed each time the function is called, where is it leaked?

I'll let @bobahop respond, but I suspect it's because Unity calls `teardown()` even after a failed test whereas the body of the test after the failure is skipped. If so, we could also fix this by freeing before performing the check (though that would be less elegant and would prevent us from using the helpful check macros).

2022-02-01 01:46 UTC, bobahop commented
From the behavior I observed, if the assert fails then no more code in that function is run, thus the free is not reached. Result is not exactly a local variable. It must be allocated memory on the heap in the program being tested to be able to return a value.

2022-02-01 01:49 UTC, bobahop commented
What I've changed to is essentially the same code that is already in phone number, which reports no memory errors on failed assertions. I don't see any reason to free before the check; just to make sure we free in the teardown, which is what it's there for, I think.

2022-02-01 02:09 UTC, ryanplusplus commented
> I don't see any reason to free before the check; just to make sure we free in the teardown, which is what it's there for, I think.

Agreed. I don't think we need to do it, I was just using that example to explain the behavior.

2022-02-01 02:09 UTC, ryanplusplus approved these changes

2022-02-01 07:07 UTC, wolf99 approved these changes

2022-02-01 07:08 UTC, merged

2022-02-01 07:12 UTC, wolf99 commented
Ah, of course! 
Great, all good then. Thanks for these fixes @bobahop ! 👌