Update test_acronym.c Fixed memory leaks
exercism/c pull request #752
Opened 2022-01-31 14:00 UTC by bobahop

`make memcheck` reported direct memory leak on failed `TEST_ASSERT_EQUAL_STRING` on my local machine (Ubuntu WSL.) Now has no memory leaks.

2022-01-31 22:50 UTC, wolf99 approved these changes

2022-01-31 22:55 UTC, wolf99 requested changes
Removing my hasty approval per my comment on

2022-02-01 01:53 UTC, bobahop commented
You're toying with me! 😄

2022-02-01 02:10 UTC, ryanplusplus approved these changes

2022-02-01 07:09 UTC, wolf99 approved these changes

2022-02-01 07:10 UTC, merged