Bob approach
exercism/c pull request #857
Opened 2023-03-10 14:44 UTC by bobahop

An approach for Bob.

2023-03-10 14:46 UTC, bobahop commented
@wolf99 and/or @ErikSchierboom: C Bob approach ready for review.

2023-03-10 19:53 UTC, wolf99 requested changes

2023-03-10 19:53 UTC, wolf99 commented on exercises/practice/bob/.approaches/answer-array/content.md
> +The `isalpha` function from `ctype.h` is used to see if `has_letters` should be set to `true`.
```suggestion
The `isalpha` function from `ctype.h` is used to see if `has_letter` should be set to `true`.
```

2023-03-10 22:37 UTC, bobahop commented
@wolf99: Thanks for the catch! Committed the change.

2023-03-11 07:33 UTC, wolf99 approved these changes

2023-03-11 07:33 UTC, merged