Hamming approach
exercism/c pull request #858
Opened 2023-03-10 16:39 UTC by bobahop

Approach for Hamming

2023-03-10 20:07 UTC, wolf99 commented
Um, seems like these are the files for Bob, not hamming?

2023-03-10 22:49 UTC, bobahop commented
Ugh! I don't know how I did it, but the files for Bob and Hamming are both in the same PR. I made the change in this PR you asked for in the original Bob PR (`has_letter`). Perhaps the changes for Hamming can be made in this PR, and when okay this can be merged and the original Bob PR can just be closed without merging? I'm wary of deleting the Bob files from here in case they somehow get deleted from the original Bob branch, too, since one may branch off the other. But I can try that if you want to merge the Bob PR first. Sorry for the mess!

2023-03-11 07:44 UTC, wolf99 requested changes

2023-03-11 07:44 UTC, wolf99 commented on exercises/practice/hamming/.approaches/increment-pointers/content.md
> +The `for` loop begins with no initialization statement.
Would be useful to explain why this is the case here.

2023-03-11 07:45 UTC, wolf99 commented
Yeesh, didn't see your comment here until after the bob or was merged. If there's issues I'll guess there'll be a merge conflict to sort out, but otherwise it may be ok.

2023-03-11 11:16 UTC, closed without merging