Resistor Color approach
exercism/c pull request #860
Opened 2023-03-10 20:24 UTC by bobahop

An approach for Resistor Color.

2023-03-10 20:27 UTC, bobahop commented
@wolf99 and/or @ErikSchierboom: C approach for Resistor Color ready for review.

2023-03-10 20:32 UTC, siebenschlaefer commented
Two small things:

- The initial `.h` file includes `<stdint.h>` and `TEST_ASSERT_EQUAL_UINT16` in the tests explicitly expects `color_code()` to return a `uint16_t`. Do you mind changing the return type from `int` to `uint16_t`?
- A function declaration like `colors()` with empty parentheses is valid C but it's actually a remnant of KR-style C that didn't declare the number or types of the parameter. Do you mind changing it to `colors(void)`?

2023-03-10 20:56 UTC, wolf99 requested changes

2023-03-10 20:56 UTC, wolf99 commented on exercises/practice/resistor-color/.approaches/introduction.md
> +# General guidance
```suggestion
## General guidance
```
Should only be one top level heading per md document.

2023-03-10 20:57 UTC, wolf99 commented
+1 to @siebenschlaefer comments

2023-03-10 22:58 UTC, bobahop commented
Thanks for the catches! All changes implemented.

2023-03-11 07:35 UTC, wolf99 approved these changes

2023-03-11 07:35 UTC, merged